### ISSUE TITLE
[feature request] 1.3.0 todo list

### ISSUE THREAD

**Issue by TheSnowfield** [KonataDev/Konata.Core#134]
#### Features
- [x] friend pic up 
- [x] friend flash pic
- [x] friend ptt
- [x] group poke (proactively)
- [x] friend poke (proactively)
- [x] group message recall
- [x] friend message recall
- [ ] ~~#130~~
- [ ] ~~#127~~
- [x] #122
- [ ] ~~send message returns a message struct(source)~~

#### Events
- [x] OnGroupMemberIncreased
- [x] OnFriendMessageRecalled
- [x] ServerKickOff
